name: Deploy to VPS

on:
  push:
    branches:
      - {{BRANCH_PRODUCTION}}

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image name (lowercase)
        run: echo "IMAGE_NAME=$(echo '${{ github.repository_owner }}/{{APP_NAME}}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "{{DEPLOY_DIR}}/{{APP_NAME}}"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export GITHUB_USER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
            cd {{DEPLOY_DIR}}/{{APP_NAME}}
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f

      - name: Health check
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Waiting for container to start..."
            sleep 10
            for i in 1 2 3 4 5; do
              STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:{{APP_PORT}}/ || true)
              if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 500 ]; then
                echo "Health check passed (HTTP $STATUS)"
                exit 0
              fi
              echo "Attempt $i: HTTP $STATUS, retrying in 5s..."
              sleep 5
            done
            echo "Health check failed after 5 attempts"
            docker logs {{APP_NAME}} --tail 20
            exit 1
