name: Trigger Release

on:
  push:
    tags:
      - 'v*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger proxy repo release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.{{CHECKOUT_TOKEN_SECRET}} }}
          repository: {{PROXY_REPO_OWNER}}/{{PROXY_REPO_NAME}}
          event-type: release
          client-payload: '{"ref": "${{ github.ref }}", "tag": "${{ github.ref_name }}", "repo": "${{ github.repository }}"}'
