import { execSync } from 'child_process';
import chalk from 'chalk';
import { ProxyRepoConfig, EXIT_PROXY_REPO_FAILED } from './types';

interface PushResult {
  path: string;
  created: boolean;
  updated: boolean;
}

/**
 * Push a workflow file to a GitHub repo via the Contents API.
 * Uses `gh api` so the user's existing `gh auth` session is reused.
 *
 * If the file already exists, its SHA is fetched first for an update.
 * If the repo doesn't exist, we attempt to create it as a public repo.
 */
export function pushWorkflowToGitHub(
  owner: string,
  repo: string,
  filePath: string,
  content: string,
): PushResult {
  const fullRepo = `${owner}/${repo}`;

  // Ensure the proxy repo exists
  ensureProxyRepoExists(owner, repo);

  // Check if file already exists (to get SHA for update)
  let existingSha: string | undefined;
  try {
    const existing = execSync(
      `gh api repos/${fullRepo}/contents/${filePath} --jq .sha`,
      { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
    ).trim();
    if (existing) existingSha = existing;
  } catch {
    // File doesn't exist yet — that's fine
  }

  // Base64 encode the content
  const base64Content = Buffer.from(content, 'utf-8').toString('base64');

  // Build the API request body
  const message = existingSha
    ? `chore: update ${filePath} (deploy-setup)`
    : `chore: add ${filePath} (deploy-setup)`;

  const body: Record<string, string> = {
    message,
    content: base64Content,
  };
  if (existingSha) {
    body.sha = existingSha;
  }

  const bodyJson = JSON.stringify(body);

  try {
    execSync(
      `gh api repos/${fullRepo}/contents/${filePath} -X PUT --input -`,
      {
        input: bodyJson,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
      },
    );

    const action = existingSha ? '更新' : '创建';
    console.log(chalk.green(`  ✔ ${action}: ${fullRepo}/${filePath}`));

    return {
      path: filePath,
      created: !existingSha,
      updated: !!existingSha,
    };
  } catch (err: any) {
    const stderr = err.stderr?.toString() || err.message;
    console.log(chalk.red(`  ✗ 推送失败: ${fullRepo}/${filePath}`));
    console.log(chalk.red(`    ${stderr}`));
    throw new Error(`Failed to push workflow to ${fullRepo}: ${stderr}`);
  }
}

/**
 * Ensure the proxy repo exists. If not, create it as a public repo.
 */
function ensureProxyRepoExists(owner: string, repo: string): void {
  const fullRepo = `${owner}/${repo}`;

  try {
    execSync(`gh repo view ${fullRepo} --json name`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    // Repo exists
  } catch {
    console.log(chalk.cyan(`  📦 创建 proxy repo: ${fullRepo}`));
    try {
      // Determine if owner is a user or org
      let createCmd: string;
      try {
        execSync(`gh api orgs/${owner} --jq .login`, {
          encoding: 'utf-8',
          stdio: ['pipe', 'pipe', 'pipe'],
        });
        // It's an org
        createCmd = `gh repo create ${fullRepo} --public --description "CI/CD proxy repo for ${repo.replace('-releases', '')} (auto-generated by deploy-setup)"`;
      } catch {
        // It's a user
        createCmd = `gh repo create ${repo} --public --description "CI/CD proxy repo for ${repo.replace('-releases', '')} (auto-generated by deploy-setup)"`;
      }

      execSync(createCmd, {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      console.log(chalk.green(`  ✔ Proxy repo 已创建: ${fullRepo}`));
    } catch (err: any) {
      throw new Error(
        `无法创建 proxy repo ${fullRepo}: ${err.stderr?.toString() || err.message}\n` +
        `  请手动创建: gh repo create ${fullRepo} --public`,
      );
    }
  }
}

/**
 * Push multiple workflow files to the proxy repo.
 * Returns the list of successfully pushed files.
 */
export function pushProxyWorkflows(
  config: ProxyRepoConfig,
  workflows: Array<{ path: string; content: string }>,
): PushResult[] {
  console.log(chalk.cyan(`\n🔀 推送 workflow 到 proxy repo: ${config.owner}/${config.repo}\n`));

  const results: PushResult[] = [];
  for (const wf of workflows) {
    results.push(pushWorkflowToGitHub(config.owner, config.repo, wf.path, wf.content));
  }
  return results;
}
